//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "CLIENT_PARENT_VERSION", "CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestApp.CLIENT), "CLIENT1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestApp.CLIENT), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestApp.CONTRACT), "U_CONTRACT1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestApp.CONTRACT), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestApp.CONTRACT_DATA), "U_CONTRACT_DATA1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestApp.CONTRACT_DATA), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_CONTRACT_USER_U_CLIENT_ID", "CLIENT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestApp.CLIENT), "U_CONTRACT", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestApp.CONTRACT), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TestApp.CONTRACT), "U_CONTRACT_DATA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestApp.CONTRACT_DATA), true)]

#endregion

namespace TestApp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CLIENT> CLIENTs
        {
            get
            {
                if ((_CLIENTs == null))
                {
                    _CLIENTs = base.CreateObjectSet<CLIENT>("CLIENTs");
                }
                return _CLIENTs;
            }
        }
        private ObjectSet<CLIENT> _CLIENTs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CONTRACT> U_CONTRACT
        {
            get
            {
                if ((_U_CONTRACT == null))
                {
                    _U_CONTRACT = base.CreateObjectSet<CONTRACT>("U_CONTRACT");
                }
                return _U_CONTRACT;
            }
        }
        private ObjectSet<CONTRACT> _U_CONTRACT;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CONTRACT_DATA> U_CONTRACT_DATA
        {
            get
            {
                if ((_U_CONTRACT_DATA == null))
                {
                    _U_CONTRACT_DATA = base.CreateObjectSet<CONTRACT_DATA>("U_CONTRACT_DATA");
                }
                return _U_CONTRACT_DATA;
            }
        }
        private ObjectSet<CONTRACT_DATA> _U_CONTRACT_DATA;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CLIENTs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCLIENTs(CLIENT cLIENT)
        {
            base.AddObject("CLIENTs", cLIENT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the U_CONTRACT EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToU_CONTRACT(CONTRACT cONTRACT)
        {
            base.AddObject("U_CONTRACT", cONTRACT);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the U_CONTRACT_DATA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToU_CONTRACT_DATA(CONTRACT_DATA cONTRACT_DATA)
        {
            base.AddObject("U_CONTRACT_DATA", cONTRACT_DATA);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CLIENT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CLIENT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CLIENT object.
        /// </summary>
        /// <param name="cLIENT_ID">Initial value of the CLIENT_ID property.</param>
        public static CLIENT CreateCLIENT(global::System.Int64 cLIENT_ID)
        {
            CLIENT cLIENT = new CLIENT();
            cLIENT.CLIENT_ID = cLIENT_ID;
            return cLIENT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CLIENT_ID
        {
            get
            {
                return _CLIENT_ID;
            }
            set
            {
                if (_CLIENT_ID != value)
                {
                    OnCLIENT_IDChanging(value);
                    ReportPropertyChanging("CLIENT_ID");
                    _CLIENT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CLIENT_ID");
                    OnCLIENT_IDChanged();
                }
            }
        }
        private global::System.Int64 _CLIENT_ID;
        partial void OnCLIENT_IDChanging(global::System.Int64 value);
        partial void OnCLIENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GROUP_ID
        {
            get
            {
                return _GROUP_ID;
            }
            set
            {
                OnGROUP_IDChanging(value);
                ReportPropertyChanging("GROUP_ID");
                _GROUP_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUP_ID");
                OnGROUP_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _GROUP_ID;
        partial void OnGROUP_IDChanging(Nullable<global::System.Int64> value);
        partial void OnGROUP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION
        {
            get
            {
                return _VERSION;
            }
            set
            {
                OnVERSIONChanging(value);
                ReportPropertyChanging("VERSION");
                _VERSION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION");
                OnVERSIONChanged();
            }
        }
        private global::System.String _VERSION;
        partial void OnVERSIONChanging(global::System.String value);
        partial void OnVERSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BAD_DEBT
        {
            get
            {
                return _BAD_DEBT;
            }
            set
            {
                OnBAD_DEBTChanging(value);
                ReportPropertyChanging("BAD_DEBT");
                _BAD_DEBT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BAD_DEBT");
                OnBAD_DEBTChanged();
            }
        }
        private global::System.String _BAD_DEBT;
        partial void OnBAD_DEBTChanging(global::System.String value);
        partial void OnBAD_DEBTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION_STATUS
        {
            get
            {
                return _VERSION_STATUS;
            }
            set
            {
                OnVERSION_STATUSChanging(value);
                ReportPropertyChanging("VERSION_STATUS");
                _VERSION_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION_STATUS");
                OnVERSION_STATUSChanged();
            }
        }
        private global::System.String _VERSION_STATUS;
        partial void OnVERSION_STATUSChanging(global::System.String value);
        partial void OnVERSION_STATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CLIENT_DISCOUNT
        {
            get
            {
                return _CLIENT_DISCOUNT;
            }
            set
            {
                OnCLIENT_DISCOUNTChanging(value);
                ReportPropertyChanging("CLIENT_DISCOUNT");
                _CLIENT_DISCOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLIENT_DISCOUNT");
                OnCLIENT_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Decimal> _CLIENT_DISCOUNT;
        partial void OnCLIENT_DISCOUNTChanging(Nullable<global::System.Decimal> value);
        partial void OnCLIENT_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PARENT_VERSION_ID
        {
            get
            {
                return _PARENT_VERSION_ID;
            }
            set
            {
                OnPARENT_VERSION_IDChanging(value);
                ReportPropertyChanging("PARENT_VERSION_ID");
                _PARENT_VERSION_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARENT_VERSION_ID");
                OnPARENT_VERSION_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _PARENT_VERSION_ID;
        partial void OnPARENT_VERSION_IDChanging(Nullable<global::System.Int64> value);
        partial void OnPARENT_VERSION_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLIENT_TYPE
        {
            get
            {
                return _CLIENT_TYPE;
            }
            set
            {
                OnCLIENT_TYPEChanging(value);
                ReportPropertyChanging("CLIENT_TYPE");
                _CLIENT_TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLIENT_TYPE");
                OnCLIENT_TYPEChanged();
            }
        }
        private global::System.String _CLIENT_TYPE;
        partial void OnCLIENT_TYPEChanging(global::System.String value);
        partial void OnCLIENT_TYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CLIENT_CODE
        {
            get
            {
                return _CLIENT_CODE;
            }
            set
            {
                OnCLIENT_CODEChanging(value);
                ReportPropertyChanging("CLIENT_CODE");
                _CLIENT_CODE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CLIENT_CODE");
                OnCLIENT_CODEChanged();
            }
        }
        private global::System.String _CLIENT_CODE;
        partial void OnCLIENT_CODEChanging(global::System.String value);
        partial void OnCLIENT_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String U_LOCATION_CONTRACTDOCUMEN
        {
            get
            {
                return _U_LOCATION_CONTRACTDOCUMEN;
            }
            set
            {
                OnU_LOCATION_CONTRACTDOCUMENChanging(value);
                ReportPropertyChanging("U_LOCATION_CONTRACTDOCUMEN");
                _U_LOCATION_CONTRACTDOCUMEN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("U_LOCATION_CONTRACTDOCUMEN");
                OnU_LOCATION_CONTRACTDOCUMENChanged();
            }
        }
        private global::System.String _U_LOCATION_CONTRACTDOCUMEN;
        partial void OnU_LOCATION_CONTRACTDOCUMENChanging(global::System.String value);
        partial void OnU_LOCATION_CONTRACTDOCUMENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String U_CONTRACT_FILE_NAME
        {
            get
            {
                return _U_CONTRACT_FILE_NAME;
            }
            set
            {
                OnU_CONTRACT_FILE_NAMEChanging(value);
                ReportPropertyChanging("U_CONTRACT_FILE_NAME");
                _U_CONTRACT_FILE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("U_CONTRACT_FILE_NAME");
                OnU_CONTRACT_FILE_NAMEChanged();
            }
        }
        private global::System.String _U_CONTRACT_FILE_NAME;
        partial void OnU_CONTRACT_FILE_NAMEChanging(global::System.String value);
        partial void OnU_CONTRACT_FILE_NAMEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CLIENT_PARENT_VERSION", "CLIENT1")]
        public EntityCollection<CLIENT> CLIENT1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CLIENT>("Model.CLIENT_PARENT_VERSION", "CLIENT1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CLIENT>("Model.CLIENT_PARENT_VERSION", "CLIENT1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "CLIENT_PARENT_VERSION", "CLIENT")]
        public CLIENT CLIENT2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("Model.CLIENT_PARENT_VERSION", "CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("Model.CLIENT_PARENT_VERSION", "CLIENT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENT> CLIENT2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("Model.CLIENT_PARENT_VERSION", "CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENT>("Model.CLIENT_PARENT_VERSION", "CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_USER_U_CLIENT_ID", "U_CONTRACT")]
        public EntityCollection<CONTRACT> U_CONTRACT_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CONTRACT>("Model.FK_CONTRACT_USER_U_CLIENT_ID", "U_CONTRACT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CONTRACT>("Model.FK_CONTRACT_USER_U_CLIENT_ID", "U_CONTRACT", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CONTRACT")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CONTRACT : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CONTRACT object.
        /// </summary>
        /// <param name="u_CONTRACT_ID">Initial value of the U_CONTRACT_ID property.</param>
        public static CONTRACT CreateCONTRACT(global::System.Int64 u_CONTRACT_ID)
        {
            CONTRACT cONTRACT = new CONTRACT();
            cONTRACT.U_CONTRACT_ID = u_CONTRACT_ID;
            return cONTRACT;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 U_CONTRACT_ID
        {
            get
            {
                return _U_CONTRACT_ID;
            }
            set
            {
                if (_U_CONTRACT_ID != value)
                {
                    OnU_CONTRACT_IDChanging(value);
                    ReportPropertyChanging("U_CONTRACT_ID");
                    _U_CONTRACT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("U_CONTRACT_ID");
                    OnU_CONTRACT_IDChanged();
                }
            }
        }
        private global::System.Int64 _U_CONTRACT_ID;
        partial void OnU_CONTRACT_IDChanging(global::System.Int64 value);
        partial void OnU_CONTRACT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION
        {
            get
            {
                return _VERSION;
            }
            set
            {
                OnVERSIONChanging(value);
                ReportPropertyChanging("VERSION");
                _VERSION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION");
                OnVERSIONChanged();
            }
        }
        private global::System.String _VERSION;
        partial void OnVERSIONChanging(global::System.String value);
        partial void OnVERSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION_STATUS
        {
            get
            {
                return _VERSION_STATUS;
            }
            set
            {
                OnVERSION_STATUSChanging(value);
                ReportPropertyChanging("VERSION_STATUS");
                _VERSION_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION_STATUS");
                OnVERSION_STATUSChanged();
            }
        }
        private global::System.String _VERSION_STATUS;
        partial void OnVERSION_STATUSChanging(global::System.String value);
        partial void OnVERSION_STATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GROUP_ID
        {
            get
            {
                return _GROUP_ID;
            }
            set
            {
                OnGROUP_IDChanging(value);
                ReportPropertyChanging("GROUP_ID");
                _GROUP_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUP_ID");
                OnGROUP_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _GROUP_ID;
        partial void OnGROUP_IDChanging(Nullable<global::System.Int64> value);
        partial void OnGROUP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PARENT_VERSION_ID
        {
            get
            {
                return _PARENT_VERSION_ID;
            }
            set
            {
                OnPARENT_VERSION_IDChanging(value);
                ReportPropertyChanging("PARENT_VERSION_ID");
                _PARENT_VERSION_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARENT_VERSION_ID");
                OnPARENT_VERSION_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _PARENT_VERSION_ID;
        partial void OnPARENT_VERSION_IDChanging(Nullable<global::System.Int64> value);
        partial void OnPARENT_VERSION_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> U_CLIENT_ID
        {
            get
            {
                return _U_CLIENT_ID;
            }
            set
            {
                OnU_CLIENT_IDChanging(value);
                ReportPropertyChanging("U_CLIENT_ID");
                _U_CLIENT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_CLIENT_ID");
                OnU_CLIENT_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _U_CLIENT_ID;
        partial void OnU_CLIENT_IDChanging(Nullable<global::System.Int64> value);
        partial void OnU_CLIENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> U_CONFIRM_DATE
        {
            get
            {
                return _U_CONFIRM_DATE;
            }
            set
            {
                OnU_CONFIRM_DATEChanging(value);
                ReportPropertyChanging("U_CONFIRM_DATE");
                _U_CONFIRM_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_CONFIRM_DATE");
                OnU_CONFIRM_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _U_CONFIRM_DATE;
        partial void OnU_CONFIRM_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnU_CONFIRM_DATEChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT1")]
        public EntityCollection<CONTRACT> U_CONTRACT1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CONTRACT>("Model.FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CONTRACT>("Model.FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT")]
        public CONTRACT U_CONTRACT2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT>("Model.FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT>("Model.FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CONTRACT> U_CONTRACT2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT>("Model.FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CONTRACT>("Model.FK_CONTRACT_PARENT_VERSION_ID", "U_CONTRACT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_USER_U_CLIENT_ID", "CLIENT")]
        public CLIENT CLIENT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("Model.FK_CONTRACT_USER_U_CLIENT_ID", "CLIENT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("Model.FK_CONTRACT_USER_U_CLIENT_ID", "CLIENT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CLIENT> CLIENTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CLIENT>("Model.FK_CONTRACT_USER_U_CLIENT_ID", "CLIENT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CLIENT>("Model.FK_CONTRACT_USER_U_CLIENT_ID", "CLIENT", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT_DATA")]
        public EntityCollection<CONTRACT_DATA> U_CONTRACT_DATA_USER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT_DATA", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CONTRACT_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CONTRACT_DATA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CONTRACT_DATA object.
        /// </summary>
        /// <param name="u_CONTRACT_DATA_ID">Initial value of the U_CONTRACT_DATA_ID property.</param>
        public static CONTRACT_DATA CreateCONTRACT_DATA(global::System.Int64 u_CONTRACT_DATA_ID)
        {
            CONTRACT_DATA cONTRACT_DATA = new CONTRACT_DATA();
            cONTRACT_DATA.U_CONTRACT_DATA_ID = u_CONTRACT_DATA_ID;
            return cONTRACT_DATA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 U_CONTRACT_DATA_ID
        {
            get
            {
                return _U_CONTRACT_DATA_ID;
            }
            set
            {
                if (_U_CONTRACT_DATA_ID != value)
                {
                    OnU_CONTRACT_DATA_IDChanging(value);
                    ReportPropertyChanging("U_CONTRACT_DATA_ID");
                    _U_CONTRACT_DATA_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("U_CONTRACT_DATA_ID");
                    OnU_CONTRACT_DATA_IDChanged();
                }
            }
        }
        private global::System.Int64 _U_CONTRACT_DATA_ID;
        partial void OnU_CONTRACT_DATA_IDChanging(global::System.Int64 value);
        partial void OnU_CONTRACT_DATA_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPTION
        {
            get
            {
                return _DESCRIPTION;
            }
            set
            {
                OnDESCRIPTIONChanging(value);
                ReportPropertyChanging("DESCRIPTION");
                _DESCRIPTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPTION");
                OnDESCRIPTIONChanged();
            }
        }
        private global::System.String _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(global::System.String value);
        partial void OnDESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION
        {
            get
            {
                return _VERSION;
            }
            set
            {
                OnVERSIONChanging(value);
                ReportPropertyChanging("VERSION");
                _VERSION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION");
                OnVERSIONChanged();
            }
        }
        private global::System.String _VERSION;
        partial void OnVERSIONChanging(global::System.String value);
        partial void OnVERSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VERSION_STATUS
        {
            get
            {
                return _VERSION_STATUS;
            }
            set
            {
                OnVERSION_STATUSChanging(value);
                ReportPropertyChanging("VERSION_STATUS");
                _VERSION_STATUS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VERSION_STATUS");
                OnVERSION_STATUSChanged();
            }
        }
        private global::System.String _VERSION_STATUS;
        partial void OnVERSION_STATUSChanging(global::System.String value);
        partial void OnVERSION_STATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GROUP_ID
        {
            get
            {
                return _GROUP_ID;
            }
            set
            {
                OnGROUP_IDChanging(value);
                ReportPropertyChanging("GROUP_ID");
                _GROUP_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUP_ID");
                OnGROUP_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _GROUP_ID;
        partial void OnGROUP_IDChanging(Nullable<global::System.Int64> value);
        partial void OnGROUP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PARENT_VERSION_ID
        {
            get
            {
                return _PARENT_VERSION_ID;
            }
            set
            {
                OnPARENT_VERSION_IDChanging(value);
                ReportPropertyChanging("PARENT_VERSION_ID");
                _PARENT_VERSION_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARENT_VERSION_ID");
                OnPARENT_VERSION_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _PARENT_VERSION_ID;
        partial void OnPARENT_VERSION_IDChanging(Nullable<global::System.Int64> value);
        partial void OnPARENT_VERSION_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String U_REMARKS
        {
            get
            {
                return _U_REMARKS;
            }
            set
            {
                OnU_REMARKSChanging(value);
                ReportPropertyChanging("U_REMARKS");
                _U_REMARKS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("U_REMARKS");
                OnU_REMARKSChanged();
            }
        }
        private global::System.String _U_REMARKS;
        partial void OnU_REMARKSChanging(global::System.String value);
        partial void OnU_REMARKSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> U_FINAL_PRICE
        {
            get
            {
                return _U_FINAL_PRICE;
            }
            set
            {
                OnU_FINAL_PRICEChanging(value);
                ReportPropertyChanging("U_FINAL_PRICE");
                _U_FINAL_PRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_FINAL_PRICE");
                OnU_FINAL_PRICEChanged();
            }
        }
        private Nullable<global::System.Decimal> _U_FINAL_PRICE;
        partial void OnU_FINAL_PRICEChanging(Nullable<global::System.Decimal> value);
        partial void OnU_FINAL_PRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> U_TEST_TEMPLATE_ID
        {
            get
            {
                return _U_TEST_TEMPLATE_ID;
            }
            set
            {
                OnU_TEST_TEMPLATE_IDChanging(value);
                ReportPropertyChanging("U_TEST_TEMPLATE_ID");
                _U_TEST_TEMPLATE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_TEST_TEMPLATE_ID");
                OnU_TEST_TEMPLATE_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _U_TEST_TEMPLATE_ID;
        partial void OnU_TEST_TEMPLATE_IDChanging(Nullable<global::System.Int64> value);
        partial void OnU_TEST_TEMPLATE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> U_CONTRACT_ID
        {
            get
            {
                return _U_CONTRACT_ID;
            }
            set
            {
                OnU_CONTRACT_IDChanging(value);
                ReportPropertyChanging("U_CONTRACT_ID");
                _U_CONTRACT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("U_CONTRACT_ID");
                OnU_CONTRACT_IDChanged();
            }
        }
        private Nullable<global::System.Int64> _U_CONTRACT_ID;
        partial void OnU_CONTRACT_IDChanging(Nullable<global::System.Int64> value);
        partial void OnU_CONTRACT_IDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA1")]
        public EntityCollection<CONTRACT_DATA> U_CONTRACT_DATA1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA")]
        public CONTRACT_DATA U_CONTRACT_DATA2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CONTRACT_DATA> U_CONTRACT_DATA2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CONTRACT_DATA>("Model.FK_CONTRACT_DATA_PARENT_VERSIO", "U_CONTRACT_DATA", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT")]
        public CONTRACT U_CONTRACT
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT>("Model.FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT>("Model.FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CONTRACT> U_CONTRACTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CONTRACT>("Model.FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CONTRACT>("Model.FK_CONTRACT_DATA_USER_U_CONTRA", "U_CONTRACT", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
